name: Build and deploy docker

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image using secrets and variables
        run: |
          docker build --build-arg NODE_USE=${{ vars.NODE_USE }} --build-arg NODE_ENV=${{ vars.NODE_ENV }} --build-arg API_KEY=${{ secrets.API_KEY }} -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.run_id }} .

      - name: Push Docker image
        run: |
          docker push  ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.run_id }}
