name: multi trigger

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-multi:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: display Trigger info
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
