name: variables

on:
  workflow_dispatch:

jobs:
  variables:
    runs-on: self-hosted
    env:
      CUSTOM: "training"

    steps:
      - name: Print default variables
        run: printenv

      - name: Print custom varaiable
        run: echo "custom variable is $CUSTOM"

